# Generated by Django 3.0.4 on 2020-03-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
        ('usuarios', '0002_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='restaurante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resto.Restaurante'),
        ),
    ]
