# Generated by Django 3.0.4 on 2020-03-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_auto_20200311_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='apertura',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='cierre',
            field=models.TimeField(null=True),
        ),
    ]
