# Generated by Django 3.0.4 on 2020-03-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_auto_20200311_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/'),
        ),
    ]
