# Generated by Django 3.0.4 on 2020-03-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_auto_20200313_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='covers/%Y/%m/%D/'),
        ),
    ]
