# Generated by Django 3.0.4 on 2020-03-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0006_auto_20200313_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='platos',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='platos',
            field=models.ManyToManyField(blank=True, to='resto.Plato'),
        ),
    ]
